version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./api
    command: python wsgi.py
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db